src/AutoMerge/cron.jl

This solves part (but not all) of #8.
Specifically, it removes a superfluous comment, as discussed here: https://github.com/JuliaRegistries/GeneralRegistryCI.jl/issues/8#issuecomment-542634516

Remove superfluous comment

---

src/AutoMerge/guidelines.jl

Sort the list of dependencies before printing it in a comment

---

src/AutoMerge/semver.jl

Fix a mistake I made in the "patch release does not narrow Julia compat"

---

src/AutoMerge/cron.jl

Fix a typo in the `pr_has_no_blocking_comments` function

---

src/AutoMerge/guidelines.jl

This is the first attempt at tackling #52

Do not use the system Python

---

src/AutoMerge/util.jl

Tried to be a bit more concise.
Fixes #8 
Closes #79

Reduce comment verbosity, fixes #8.

---

src/AutoMerge/AutoMerge.jl
src/AutoMerge/ciservice.jl
src/AutoMerge/cron.jl
src/AutoMerge/new-package.jl
src/AutoMerge/new-version.jl
src/AutoMerge/public.jl
src/AutoMerge/pull-requests.jl
src/AutoMerge/util.jl
test/automerge-integration.jl
test/automerge-unit.jl

Fixes #5 
Better reviewed with white-space changes hidden: https://github.com/JuliaRegistries/RegistryCI.jl/pull/80/files?w=1

Enable running from GitHub Actions.

---

src/AutoMerge/github.jl

Wait for GitHub to finish the "mergeability computation" before merging

---

src/AutoMerge/cron.jl

Process PRs from oldest to newest

---

README.md

Copied from https://github.com/JuliaRegistries/General/issues/3673
with minor formatting changes (a bit more compact), added
clarifications for all questions which came up in the related
discussion
https://discourse.julialang.org/t/announcement-automatic-merging-for-the-general-registry/29961

Add automatic merging guidelines to the README.

---

src/AutoMerge/new-package.jl
src/AutoMerge/new-version.jl

Exit with non-zero status code if the guidelines were not met

---

Project.toml
src/AutoMerge/guidelines.jl

Better warning when a patch changes Julia compat

---

src/AutoMerge/cron.jl
test/automerge-integration.jl

Use the `automerge/decision` status to decide whether or not to merge

---

Project.toml
src/AutoMerge/jll.jl
src/AutoMerge/new-package.jl
src/AutoMerge/new-version.jl

Enable automerging for JLL packages

---

Project.toml
src/AutoMerge/guidelines.jl

For new version PRs, check that the version doesn’t already exist

---

Project.toml
src/AutoMerge/guidelines.jl
src/AutoMerge/new-package.jl
src/AutoMerge/new-version.jl

Fix several JLL-related bugs

---

Project.toml
src/AutoMerge/automerge_comment.jl
src/AutoMerge/github.jl
src/AutoMerge/new-package.jl
src/AutoMerge/new-version.jl

Update the original comment instead of always posting a new separate comment

---

Project.toml
src/AutoMerge/public.jl
src/RegistryCI.jl
src/registry_testing.jl
src/utils.jl
test/registryci_registry_testing.jl

Staging for pull request #194 
cc: @BenJWard

Staging for pull request #194 

---

Project.toml
src/AutoMerge/guidelines.jl
src/AutoMerge/new-package.jl
src/AutoMerge/new-version.jl
src/AutoMerge/public.jl
src/AutoMerge/pull-requests.jl

AutoMerge: allow custom registries to depend on external registries

---

Project.toml
src/AutoMerge/guidelines.jl
src/AutoMerge/new-package.jl

Allow JLL packages to start with a lowercase letter 

---

Project.toml
src/AutoMerge/util.jl

Staging for #226 

---

Project.toml
src/AutoMerge/new-package.jl
src/AutoMerge/util.jl

Here my try at improving the message.

Update NewPackage() message for _jll

---

Project.toml
src/AutoMerge/guidelines.jl
src/AutoMerge/new-package.jl
test/automerge-unit.jl

Fixes https://github.com/JuliaRegistries/RegistryCI.jl/issues/112 and addresses @StefanKarpinski's comment https://github.com/JuliaRegistries/RegistryCI.jl/issues/285#issuecomment-718930717

Add "julia" check

---

.travis.yml
Project.toml
test/runtests.jl

Run CI on Julia nightly, but don't run the TagBot trigger tests on Julia nightly

---

Project.toml
src/AutoMerge/github.jl

Don't unnecessarily print an error that we are intentionally ignoring

---

Project.toml
src/TagBot/fixup.jl

Fixes https://github.com/JuliaRegistries/General/issues/27670

Put the TagBot "fixup PR" inside a try-catch block

---

Project.toml
src/AutoMerge/new-package.jl
src/AutoMerge/new-version.jl

Similar to #315 but on a smaller scale. In this case `git log -p -w` is good for reviewing.

Reduce nesting of if expressions.

---

src/AutoMerge/automerge_comment.jl
src/AutoMerge/cron.jl
src/AutoMerge/github.jl
src/AutoMerge/guidelines.jl
src/AutoMerge/jll.jl

A couple of small code simplifications.

Small simplifications

---

src/AutoMerge/new-package.jl
src/AutoMerge/new-version.jl

Followup to #318, making the collection and processing of guidelines a lot nicer.

Nicer collection and processing of guidelines.

---

Project.toml
src/registry_testing.jl

Better error message when one or more dependencies does not exist in the General registry

---

.github/workflows/ci_unit.yml
README.md
bors.toml
docs/Project.toml
docs/make.jl
docs/src/guidelines.md
docs/src/index.md
docs/src/internals.md
docs/src/private-registries.md
docs/src/public.md
docs/src/regexes.md
src/AutoMerge/public.jl
test/automerge-unit.jl

Use Documenter for the docs

---

README.md

For me, this makes it a little bit easier to read.

README: Put the CI badges in a table

---

src/AutoMerge/guidelines.jl

Fixes #400.
I did not bump the version to avoid conflicts with #407

Set `JULIA_PKG_PRECOMPILE_AUTO` env variable

---

docs/src/private-registries.md

I've added some notes documenting some of the configuration details that I've recently learn about on the #github-actions slack channel.

More details regarding custom registries

---

src/AutoMerge/guidelines.jl

Ref https://github.com/JuliaRegistries/RegistryCI.jl/issues/455#issuecomment-1206545988

Fix docs for `guideline_patch_release_does_not_narrow_julia_compat`

---

src/AutoMerge/guidelines.jl

Closes https://github.com/JuliaRegistries/RegistryCI.jl/pull/436

Change "upper bounded" to "upper-bounded"

---

docs/src/private-registries.md

Documentation: fix a typo in `private-registries.md`

---

src/AutoMerge/changed_files.jl

Fixes https://github.com/JuliaRegistries/General/pull/75847#issuecomment-1385548064

allow modifying weak toml files

---

Project.toml
src/AutoMerge/semver.jl
test/automerge-unit.jl

Introduced in #495 
Ref https://github.com/JuliaRegistries/General/pull/78512#issue-1599785208

Fix breakage in the `julia_compat` function

---

docs/Project.toml

Just so that we can get CI to be green again.

Fix Documenter

---

src/AutoMerge/guidelines.jl

Maybe this will help users look at the correct logs.

Change "CI logs" to "AutoMerge" logs

---

src/AutoMerge/guidelines.jl
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_false_version_0.1.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_false_version_0.1.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_false_version_1.0.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_false_version_1.0.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_true_version_0.1.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_true_version_0.1.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_true_version_1.0.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_true_version_1.0.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_false_version_0.1.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_false_version_0.1.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_false_version_1.0.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_false_version_1.0.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_true_version_0.1.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_true_version_0.1.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_true_version_1.0.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_true_version_1.0.0_point_to_slack_true.md

followup to #566 to address review feedback in https://github.com/JuliaRegistries/RegistryCI.jl/pull/566#issuecomment-2190179011

add link to registryci docs

---

src/registry_testing.jl

Ref https://github.com/JuliaRegistries/General/issues/104849

Registry consistency tests: In `Compat.toml`, make sure that each compat spec is a valid registry compat spec

---

.github/dependabot.yml
.github/workflows/ci_integration.yml
.github/workflows/ci_unit.yml
.github/workflows/format_pr.yml

* Install dependabot
* Update various external workflows
* Use `julia-actions/cache` instead of `actions/cache`

[CI] Some updates to GitHub Actions setup

---

Project.toml
src/AutoMerge/guidelines.jl
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_false_version_0.1.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_false_version_0.1.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_false_version_1.0.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_false_version_1.0.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_true_version_0.1.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_true_version_0.1.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_true_version_1.0.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_true_version_1.0.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_false_version_0.1.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_false_version_0.1.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_false_version_1.0.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_false_version_1.0.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_true_version_0.1.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_true_version_0.1.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_true_version_1.0.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_true_version_1.0.0_point_to_slack_true.md

These were the wrong way around. (Sorry, should've caught it in my review @ericphanson)

Fix guidance if branches

---

Project.toml
src/AutoMerge/guidelines.jl
test/automerge-unit.jl
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_false_version_0.1.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_false_version_0.1.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_false_version_1.0.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_false_version_1.0.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_true_version_0.1.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_true_version_0.1.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_true_version_1.0.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_package_suggest_onepointzero_true_version_1.0.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_false_version_0.1.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_false_version_0.1.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_false_version_1.0.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_false_version_1.0.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_true_version_0.1.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_true_version_0.1.0_point_to_slack_true.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_true_version_1.0.0_point_to_slack_false.md
test/reference_comments/comment_pass_false_type_new_version_suggest_onepointzero_true_version_1.0.0_point_to_slack_true.md

issue reported on slack: https://julialang.slack.com/archives/C6M4DQA5P/p1738738557109929

Improve automerge error message for breaking changes

---

.github/workflows/ci_integration.yml
.github/workflows/ci_unit.yml

AutoMerge: update CI to match checks

---

AutoMerge.jl/src/dependency_confusion.jl
AutoMerge.jl/src/guidelines.jl
AutoMerge.jl/src/jll.jl
AutoMerge.jl/src/package_path_in_registry.jl
AutoMerge.jl/src/semver.jl
AutoMerge.jl/src/toml.jl
AutoMerge.jl/src/util.jl

Prepares for https://github.com/JuliaRegistries/RegistryCI.jl/issues/453#issuecomment-3330925354 but is a good idea regardless.

AutoMerge: Refactor parsing of registry toml files.

---

AutoMerge/src/juliaup.jl
AutoMerge/test/automerge-unit.jl

Only do sanity check of juliaup output on one platform.
