src/AutoMerge/cron.jl
This will allow us to write `Day(3)` instead of `Minute(4320)`.
cc: @fredrikekre
=> Replace `TimePeriod` with `Period`

src/AutoMerge/github.jl
The General registry is already configured to automatically delete merged branches. Therefore, we don't need to also do that in the automerge code.
cc: @fredrikekre
=> Don't delete branches after merging

src/AutoMerge/github.jl
If there are multiple reviews, we use the most recent one. So actually there is no need to try to delete old reviews.
Fixes #24
=> Do not delete old reviews

src/AutoMerge/github.jl, src/AutoMerge/new-package.jl, src/AutoMerge/new-version.jl
Put approve-comment in the review instead of as a separate comment, fixes #8.
=> Put approve-comment in the review

src/AutoMerge/AutoMerge.jl, src/AutoMerge/assert.jl, test/automerge-unit.jl
The documentation for the `@assert` macro says:
> Warning: An assert might be disabled at various optimization levels.
This pull request adds the `always_assert` function. `always_assert` is like `@assert`, except that `always_assert` will always run and will never be disabled.
=> Add the `always_assert` function

test/runtests.jl
If the `AUTOMERGE_RUN_INTEGRATION_TESTS` environment variable is set and its value is equal to `true`, then run the unit tests and the integration tests.
Else, run the unit tests only.
=> Always run the unit tests

.travis.yml
There are two build stages.
The first build stage only runs the unit tests. It works on PRs made from within this repo, as well as PRs made from forked repos.
The second build stage runs both the unit tests and the integration tests. It only works on PRs made from within this repo. It does not work on PRs made from forked repos.
There is no point in submitting code coverage reports from the first build stage. We should only submit coverage from the second build stage.
=> Do not submit code coverage for the first build stage

Project.toml, src/AutoMerge/guidelines.jl
May fix Gtk and dependent packages (https://github.com/JuliaRegistries/General/pull/6007, https://github.com/JuliaRegistries/General/pull/5890). Hopefully it isn't much of a burden for other packages.
=> Run all package-loads under xvfb

Project.toml, src/AutoMerge/guidelines.jl
That way, we can look at the logs and know whether or not AutoMerge found `xvfb-run` in the `PATH`.
=> Print the results of `Sys.which("xvfb-run")` as a debug message

src/AutoMerge/guidelines.jl, src/AutoMerge/jll.jl
If a non-JLL package has a JLL package as a dependency, we will not require you to have a compat entry for the JLL package.
E.g. suppose you have a package `Example.jl`. And `Example.jl` has a dependency `Foo_jll.jl`. We will not require that `Example.jl` has a compat entry for `Foo_jll.jl`.
=> If a non-JLL package has a JLL package as a dependency, we will not require you to have a compat entry for the JLL package

.travis.yml, Project.toml, src/AutoMerge/guidelines.jl, src/AutoMerge/new-package.jl, src/AutoMerge/new-version.jl
=> Make `Pkg.add("Foo")` and `import Foo` two different steps

Project.toml, test/automerge-integration-utils.jl, test/automerge-integration.jl, test/automerge-unit.jl, test/registryci_registry_testing.jl, test/runtests.jl
RegistryCI now uses GitCommand. GitCommand uses Git_jll. Git_jll uses Artifacts. And Artifacts require at least Julia 1.3. So Registry CI now requires at least Julia 1.3.
=> Require at least Julia 1.3

Project.toml, src/AutoMerge/guidelines.jl, src/AutoMerge/new-package.jl
We require package names to be at least 5 characters long to be automerged.
For JLL packages, the `_jll` part of the name should not count towards those 5 characters.
This PR fixes that bug.
=> When computing length of package name, exclude `_jll`

Project.toml, src/AutoMerge/new-package.jl, src/AutoMerge/new-version.jl, src/AutoMerge/public.jl, src/AutoMerge/pull-requests.jl, src/AutoMerge/types.jl
Fixes #189 
It is very confusing to see that automerge "passed" on a pull request, when in reality that pull request was not eligible to be evaluated for automerge, so automerge did not evaluate it and simply exited.
=> If the PR is not eligible for automerge, the job should exit with an error

Project.toml, src/AutoMerge/public.jl, src/RegistryCI.jl, src/registry_testing.jl, src/utils.jl, test/registryci_registry_testing.jl
Closes #118 
This is a redux of #118.
I've used Pkg.Registry.add as suggested by @fredrikekre, which also allowed me to use Pkg, to find and get the UUIDs from the Registry.toml files, without assuming where the registries were stored.
=> Permit specifying dependency registries

Project.toml, src/AutoMerge/guidelines.jl
=> Drop the "can’t narrow Julia compat in a patch release" requirement for pre-1.0 packages

Project.toml
I think RegistryCI.jl is stable enough at this point that we should release 1.0.0.
Fixes #95
=> Bump version number from "0.13.0" to "1.0.0"

Project.toml, src/AutoMerge/cron.jl
Currently, if Travis CI fails on a pull request but AutoMerge passes on that pull request, then every AutoMerge cron job will exit with an error.
This is very annoying because my inbox fills up with notifications that the AutoMerge cron jobs are "failing." In reality, they are not actually failing.
=> AutoMerge cron job should not exit with error if Travis CI failed on a pull request

Project.toml, bin/remember_to_update_registryci.jl, src/AutoMerge/AutoMerge.jl, src/RegistryCI.jl, src/registry_testing.jl, test/Project.toml, test/automerge-integration-utils.jl, test/automerge-integration.jl, test/automerge-unit.jl, test/registryci_registry_testing.jl, test/runtests.jl
Git_jll requires a lot of artifacts.
It is getting really annoying to have to download those every time a Travis build needs to use RegistryCI.
=> Remove the dependency on GitCommand

Project.toml, src/AutoMerge/new-package.jl
We used to require that the repo URL ended in `/PackageName.jl.git` for new package registrations.
But now we support having multiple registered packages inside a single Git repo.
So this repo URL check no longer makes sense,
This PR disables that check.
cc: @StefanKarpinski
=> Disable the "URL ends in /name.jl.git" check

Project.toml, README.md, src/AutoMerge/guidelines.jl, src/AutoMerge/new-package.jl, test/automerge-unit.jl
This follows up to #200
Rather than just making it print a message that "Its OK to end with uppercase"
this just changes it to allow it.
I don't get what the motivation of #200 was, TBH.
The requirement to not end in uppercase is not listed in the summary in 
https://github.com/JuliaRegistries/General/blob/master/README.md#automatic-merging-of-pull-requests
which says
> Package name: Should start with a capital letter, contain only ASCII alphanumeric characters, and be at least 5 characters long.
=> Allow new package names to end with uppercase

Project.toml, README.md, bin/remember_to_update_registryci.jl, src/AutoMerge/automerge_comment.jl, src/AutoMerge/changed_files.jl, src/AutoMerge/ciservice.jl, src/AutoMerge/cron.jl, src/AutoMerge/github.jl, src/AutoMerge/guidelines.jl, src/AutoMerge/new-package.jl, src/AutoMerge/new-version.jl, src/AutoMerge/public.jl, src/AutoMerge/pull-requests.jl, src/registry_testing.jl, teamcity_settings.kts, test/automerge-integration-utils.jl, test/automerge-integration.jl, test/registryci_registry_testing.jl, test/templates/feature_1/R/Requires/Versions.toml, test/templates/feature_2/R/Requires/Versions.toml, test/templates/feature_3/R/Req/Versions.toml, test/templates/feature_4/R/Requires/Versions.toml, test/templates/feature_5/R/Requires/Versions.toml, test/templates/master_2/R/Requires/Versions.toml, test/templates/master_3/R/Requires/Versions.toml
Fixes #247 
Fixes #248 
Fixes #249 
I'll keep it as drawn until https://github.com/JuliaWeb/GitHub.jl/pull/163 is merged because it is required for this to work properly.
Any feedback welcome. I hope this will make private registry more accessible by enabling such great tooling as is RegistryCI to support passing dependency registry by name without need for full URL, and allowing to parametrize the base API URI.
Later, I plan to add also support for TeamCity.
=> Improving usability for private registry, outside of github.com

Project.toml, src/AutoMerge/guidelines.jl
A few automerge jobs are failing with this error:
```
IOError: unlink: permission denied (EACCES)
Stacktrace:
[1] uv_error at ./libuv.jl:97 [inlined]
[2] unlink(::String) at ./file.jl:888
[3] rm(::String; force::Bool, recursive::Bool) at ./file.jl:268
[4] rm(::String; force::Bool, recursive::Bool) at ./file.jl:278 (repeats 5 times)
[5] (::RegistryCI.AutoMerge.var"#76#78"{String})() at /home/runner/.julia/packages/RegistryCI/1gUch/src/AutoMerge/guidelines.jl:317
[6] _atexit() at ./initdefs.jl:316
[7] exit at ./initdefs.jl:28 [inlined]
[8] _start() at ./client.jl:487
┌ Warning: temp cleanup
│   exception =
│    IOError: unlink: permission denied (EACCES)
│    Stacktrace:
│     [1] uv_error at ./libuv.jl:97 [inlined]
│     [2] unlink(::String) at ./file.jl:888
│     [3] rm(::String; …
```
=> Make temp dirs writable before deleting them

Project.toml, src/registry_testing.jl
Reenable and fix tests that check Pkg can read and understand compat and deps entries in the registry.
This thus also reverts commit 9c6f8fc2ce7393695c9040cb0ec10bd1adc1ba5f.
=> Reenable and fix tests that check Pkg can read the entries

Project.toml, src/registry_testing.jl
When tests failed here I was not able to tell from the CI logs which packages were failing. Now this is possible!
=> Give each tested package in a registry a named testset

Project.toml, src/AutoMerge/guidelines.jl, src/AutoMerge/semver.jl, test/automerge-unit.jl
I have realized that some people have `[compat]` entries of the form:
```toml
[compat]
PkgA = "0"
```
This `[compat]` entry includes an infinite number of breaking releases, which defeats the purpose of having upper-bounded `[compat]` entries.
**The good news**: [RetroCap.jl](https://github.com/bcbi/RetroCap.jl) already recognizes that these `[compat]` entries are not true upper-bounded `[compat]` entries. Therefore, when we did the recent retrocapping in https://github.com/JuliaRegistries/General/pull/11114, RetroCap.jl fixed these `[compat]` entries, replacing entries like this:
```toml
[compat]
PkgA = "0"
```
With something like this:
```toml
[compat]
PkgA = "0.0.0 - 0.3.7"
```
Where `0.3.7` would be the latest registered version of `PkgA`.
**The bad news**: AutoMerge currently …
=> Do not automerge packages that have `[compat]` entries of the form `PkgA = "0"`, etc.

Project.toml, src/AutoMerge/jll.jl
New jll packages are going to have two additional dependencies: `Artifacts` (a new stdlib in Julia v1.6, [this package](https://github.com/JuliaPackaging/Artifacts.jl) for the other versions) and [`JLLWrappers`](https://github.com/JuliaPackaging/JLLWrappers.jl).
Automerge in https://github.com/JuliaRegistries/General/pull/21815 also complains about `Artifacts.toml` not having a compat bound.  Not sure what to with that one, since it's a new stdlib, maybe we should set [v1.3](https://github.com/JuliaPackaging/Artifacts.jl/blob/258eaa57c9ec0d488c2082743644cd03b7691408/Project.toml#L3) as minimum version?
=> Allow Artifacts and JLLWrappers as deps of JLLs

Project.toml, src/AutoMerge/guidelines.jl
The AutoMerge comments have gotten way too long and wordy.
If a package does not meet the AutoMerge guidelines, I think it is very reasonable to expect that the package's author will read the General registry README. We don't need to repeat all of that information in each AutoMerge comment.
=> Make the AutoMerge comments more concise

Project.toml, src/AutoMerge/new-package.jl
Of all of the AutoMerge checks, this is the only one that I don't think is useful. In 100% of the cases in which a package fails this check, we always manually merge it anyway.
If it's not changing what we do, there's no need to have the check in the first place.
=> Disable the "standard initial version number" check

.travis.yml, Project.toml, README.md, src/AutoMerge/AutoMerge.jl, src/AutoMerge/guidelines.jl, src/AutoMerge/new-package.jl, src/AutoMerge/util.jl, test/automerge-integration.jl, test/automerge-unit.jl
My attempt to fix #10 and close #273. There's three semi-arbitrarily chosen cutoffs that might need more tuning, and if any are hit, then the package is flagged.
1. DL distance is <= 1 (which would catch Websocket vs Websockets)
2. A normalized DL distance catch long package names with more than 1 edit but only a few. I ended up going with a weird `5 + sqrt(max(len1, len2))` normalization just because it seemed like just dividing by the length made long packages get flagged too much.
3. Finally, there's the visual distance check, which can catch package names with more edits than allowed by the other checks if the edits are hard to distinguish visually, like `Jill` vs `JiII` (that's 2 edits of lowercase-ell to uppercase-eye, so the straight DL doesn't catch, short name so the normalized …
=> Add ASCII check, distance check, visual distance check

Project.toml, README.md
There's no point in having the same documentation repeated in multiple places.
I think we should just maintain this list in the General registry README. Then, other locations can just link to the General registry README.
=> Don't repeat documentation that is available elsewhere

Project.toml, src/AutoMerge/guidelines.jl, test/automerge-unit.jl
There was a really silly bug where I put `dl` instead of `dl_lowercase`, so that check wasn't correct .
This fixes that and also sorts the names and adds comment-collapse markup for > 10 packages.
Here I set the cutoff to 8 so we can see the effect of exceeding the limit:
```julia
julia> AutoMerge.meets_distance_check("MKL", all_pkg_names, comment_collapse_cutoff=8)[2] |> println
Package name similar to 10 existing packages.
<details>
<summary>Similar package names</summary>
1. Similar to HSL. Damerau-Levenshtein distance 2 is at or below cutoff of 2.
2. Similar to MLJ. Damerau-Levenshtein distance 2 is at or below cutoff of 2.
3. Similar to MD5. Damerau-Levenshtein distance 2 is at or below cutoff of 2.
4. Similar to GSL. Damerau-Levenshtein distance 2 is at or below cutoff of 2.
5. …
```
=> Sort names, collapse comment, fix bug

Project.toml, src/AutoMerge/AutoMerge.jl, src/AutoMerge/util.jl, test/automerge-unit.jl
As came up in https://github.com/JuliaRegistries/General/pull/23128
I first thought to do this by adding the stdlibs to the `all_pkg_names` variable here https://github.com/JuliaRegistries/RegistryCI.jl/blob/e4fff963024a5091b4d852fbcdab7284aab18db5/src/AutoMerge/new-package.jl#L140
But then I remembered I had added to the [General registry's docs](https://github.com/JuliaRegistries/General#automatic-merging-of-pull-requests) the following:
> To test yourself that a tentative package name, say MyPackage meets these checks, you can use the following code (after adding the RegistryCI package to your Julia environment):
> ```julia
> using RegistryCI
> using RegistryCI.AutoMerge
> all_pkg_names = AutoMerge.get_all_non_jll_package_names(path_to_registry)
> …
```
=> Check name distance to standard libraries

.travis.yml, Project.toml, src/registry_testing.jl
The signature changed for this in 1.6 and will further be changed on master. Might make sense to just use a snapshotted copy here.
=> make RegistryCI tests less reliant on Pkg internals

Project.toml, example_github_workflow_files/automerge.yml, src/AutoMerge/public.jl
When Automerge merges PRs, it does not trigger the TagBot notifier because actions can't trigger other actions with the default token. So for cron jobs, use a user token.
=> Use TagBot token for merging stuff

.github/workflows/TagBot.yml, Project.toml, src/TagBot/TagBot.jl, test/runtests.jl
Slight oversight: When looking for a closed issue by JuliaTagBot, it also includes PRs. So it picks up the PR adding the TagBot action from way back when: https://github.com/JuliaRegistries/RegistryCI.jl/pull/214
=> Filter out pull requests when looking for a trigger issue

Project.toml, src/AutoMerge/new-package.jl
If for some reason a new JLL package wants to include "julia" in its name, I think it's perfectly fine to require manual merge in that case.
=> The "new package name should not include `julia` in the name" check should apply to all packages (including JLL packages)

Project.toml, src/TagBot/TagBot.jl, test/tagbot-unit.jl
=> TagBot: Handle repos where issues are disabled

bors.toml, src/AutoMerge/guidelines.jl
Closes #245 
Lots of stuff needs HOME to work properly.
More concretely, both Git CLI and LibGit2 get their config from `$HOME/.gitconfig` by default, and that breaks when it's unset.
=> Pass HOME to subprocesses

.github/workflows/ci_integration.yml, README.md, test/automerge-integration.jl
There's not really any point in running the integration tests on the `master` branch. After all, we use Bors. And Bors only fast-forwards `master` to point to `staging` if the integration tests have already passed on `staging`. So it's redundant to run them again on `master`, since we know that they have already passed on the exact same commit that `master` now points to.
=> Only run the integration tests on the `staging` and `trying` branches

src/AutoMerge/cron.jl, src/AutoMerge/github.jl, src/AutoMerge/guidelines.jl, src/AutoMerge/jll.jl, src/AutoMerge/semver.jl
This PR removes all occurrences of `undef`. Not because there's anything wrong with `undef` but because all uses could be simplified. There should be no functional differences.
=> Simplification of code using undef.

src/AutoMerge/cron.jl
This PR simplifies the implementation of `cron_or_api_build(api, pr, registry)` by repeatedly applying the rewrite from
```
if x
y
else
z
end
return nothing
```
to
```
if !x
z
return nothing
end
y
return nothing
```
which dramatically reduces the nesting depth of the code and makes the logic easier to follow. There should be no functional differences.
Review tip: The only effective way to review is probably to apply these transformations yourself and see if you end up with the same code.
=> Simplify logic by unnesting if expressions.

Project.toml, src/AutoMerge/jll.jl, src/AutoMerge/new-package.jl, src/AutoMerge/new-version.jl, src/AutoMerge/pull-requests.jl, src/AutoMerge/types.jl
Do all authorization checks in one place.
=> Centralize authorization checks.

Project.toml, src/AutoMerge/guidelines.jl, src/AutoMerge/new-package.jl
Fixes #244 
Fixes #267 
See also: #243 
This restores the "repo URL ends in /PackageName.jl.git" check.
We only run this check if the package is not a subdirectory package.
=> If the package is in a subdirectory, check that the repo URL ends in `/PackageName.jl.git`

Project.toml, src/AutoMerge/guidelines.jl, src/AutoMerge/new-package.jl, src/AutoMerge/new-version.jl, src/AutoMerge/public.jl
Currently, if the registry tests fail, AutoMerge crashes ungracefully. This is not very helpful.
Instead, this PR makes the registry consistency tests into a regular AutoMerge check just like everything else.
=> AutoMerge should not crash if the registry consistency tests fail

Project.toml, src/AutoMerge/guidelines.jl
I tested this by
```julia
using RegistryCI
using RegistryCI.AutoMerge
using RegistryCI.AutoMerge: meets_distance_check, get_all_non_jll_package_names
registry_master = joinpath(homedir(), ".julia", "registries", "General")
other_packages = get_all_non_jll_package_names(registry_master)
pkg_name = "C"
meets_distance_check(pkg_name, other_packages)[2] |> println
```
then editing the comment in https://github.com/JuliaRegistries/General/pull/31746, copy pasting the result, and clicking preview to check that it works properly even with the spoiler tag:
=> fix indentation in pkg name similarity list

.github/workflows/VersionVigilante_bors.yml, Project.toml
When you are working on a PR, you might want to run `bors try` before you are ready to merge, just to see if the integration tests pass.
So we should not require that VersionVigilante passes on `bors try`.
We should however continue to require that VersionVigilante passes on `bors merge`.
=> Automatically pass VersionVigilante on the trying branch

src/AutoMerge/guidelines.jl, src/AutoMerge/new-package.jl, src/AutoMerge/new-version.jl
This separates the compat checks of Julia from compat of other packages.
1. To make bad Julia compat more visible in the automerge report.
2. To make additional checks, specifically that the upper bound of Julia is not 2 or higher, which is unreasonable at this time.
Currently General has 12 packages with an upper bound of "2" or "2.0". All of these are probably misunderstandings of hyphen ranges, thinking that the upper end is exclusive, e.g. "1.5 - 2.0".
Additional tests of this have not been added yet.
=> Check Julia compat separately.

src/AutoMerge/automerge_comment.jl, src/AutoMerge/cron.jl, src/AutoMerge/new-package.jl, src/AutoMerge/public.jl, src/AutoMerge/pull-requests.jl, src/AutoMerge/types.jl
closes https://github.com/JuliaRegistries/RegistryCI.jl/issues/382
I thought this would be way harder! But also I could've missed something.
I wonder if we can test this by adding a github workflow with read-only permissions like we talked about in https://github.com/JuliaRegistries/General/issues/35514, and then run the regular integration tests on that except with `read_only` set to true. What do you think?
=> add `read_only` mode

docs/src/regexes.md
With this PR, we:
1. Implement the DRY (don't repeat yourself) principle. For example, the regexes are only defined in one place.
2. Make sure that the regex documentation never gets out of sync with the source code.
=> Add some checks to make sure that the regex docs never get out of sync

README.md
Closes #403 
The Bors badge is static (i.e. the content never changes), so I went ahead and removed it.
I put everything else into the table. The docs badges are not very big, so I put both of them into the same cell.
=> README: remove the Bors badge, and put all other badges into the table

Project.toml, docs/make.jl, docs/src/guidelines.md, src/AutoMerge/AutoMerge.jl, src/AutoMerge/assert.jl, src/AutoMerge/changed_files.jl, src/AutoMerge/dependency_confusion.jl, src/AutoMerge/guidelines.jl, src/AutoMerge/jll.jl, src/AutoMerge/new-package.jl, src/AutoMerge/new-version.jl, src/AutoMerge/types.jl, src/AutoMerge/update_status.jl
Currently, we duplicate a lot of this information. For example, the guidelines themselves are defined in the source code of the `RegistryCI.jl` package (specifically in the `RegistryCI.AutoMerge` submodule), but the documentation of the guidelines is in the [General registry README](https://github.com/JuliaRegistries/General/blob/master/README.md).
With this PR, I attempt to implement the [don't repeat yourself (DRY)](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle by centralizing the definition of the guidelines and their documentation into a single place, specifically the AutoMerge source code, which is now the single source of truth.
Then, we use the AutoMerge source code to auto-generate a documentation page that has the list of AutoMerge guidelines.
Once this PR is …
=> Auto-generate the documentation page with the list of AutoMerge guidelines

Project.toml, docs/src/guidelines.md, src/AutoMerge/guidelines.jl
I've bumped the version number because the `stable` docs link is not updated unless we register and tag a new release.
=> A few tweaks to the docs for AutoMerge guidelines

src/AutoMerge/jll.jl, src/AutoMerge/util.jl
Since https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1128 we also use TOML for JLLs in some cases.
=> Allow TOML as dependency of JLL packages

Project.toml, src/AutoMerge/guidelines.jl, test/automerge-unit.jl
Instead of making the "no prereleases" check part of some other checks (like the "initial version" check and the "sequential version" check), this PR makes the "no prereleases" check its own top-level check.
=> Bug fix: restore the "no prerelease" versions check; we never meant to remove it

Project.toml, src/registry_testing.jl
Fixes #457
Will likely fail until https://github.com/JuliaRegistries/General/pull/65997 is merged.
=> Registry consistency tests: the compress roundtrip check should compare `VersionRange`s (not `String`s)

Project.toml, docs/src/regexes.md, src/AutoMerge/pull_requests.jl, test/automerge-unit.jl
This revises the commit regex to match
```
r"Commit: ([0-9a-f]+)"
```
but no longer requires that it is a markdown item on a line of its own.
The rationale is https://github.com/GunnarFarneback/LocalRegistry.jl/pull/49, which makes use of "git push options" to create a pull request (only effective on GitLab). This provides a very low complexity pull request creation mechanism but has the limitation that it cannot pass newlines.
In terms of robustness and input sanitation this change makes no difference to Registrator generated pull requests.In fact it's rather stricter since the code in total only allows the commit hash to be exactly 40 hexadecimal digits.
=> Revise the commit regex.

docs/src/guidelines.md
Added a brief note explaining that `get_all_non_jll_package_names` requires a non-default extracted General registry, as explained in #442 .
=> checking name similarity requires an extracted registry

docs/src/private-registries.md
It takes time to find out that this is even possible so I figure this is worth documenting.
=> add a note about `registry_deps` with name field

Project.toml, src/AutoMerge/guidelines.jl, test/automerge-unit.jl
closes https://github.com/JuliaRegistries/RegistryCI.jl/issues/441
=> Enforce files in `src` have distinct names after lowercasing and are allowed on all OS's

Project.toml
So that we can get https://github.com/JuliaRegistries/RegistryCI.jl/pull/488 released.
=> Bump the patch version

Project.toml, src/AutoMerge/AutoMerge.jl, src/AutoMerge/guidelines.jl, src/AutoMerge/jll.jl, src/AutoMerge/semver.jl, src/AutoMerge/toml.jl, src/registry_testing.jl
Fixes https://github.com/JuliaRegistries/RegistryTools.jl/issues/81
Fixes #494
=> Allow the `Deps.toml`, `WeakDeps.toml`, and `Compat.toml`, and `WeakCompat.toml` files to not exist

Project.toml, src/AutoMerge/guidelines.jl
This is a bug-fix. This guideline was always intended to exclude non-alphanumeric characters; we just weren't doing that correctly.
=> Alphanumeric name check: Don't use `\w`, because we don't want to include underscores

src/TagBot/TagBot.jl, test/tagbot-unit.jl
Calling `repo_and_version_of_pull_request_body` with an empty body causes errors due to `occursin` not handling `Nothing` values.
```julia
ERROR: MethodError: no method matching occursin(::String, ::Nothing)
Closest candidates are:
occursin(::Union{AbstractChar, AbstractString}, ::AbstractString) at strings/search.jl:628
occursin(::Any) at strings/search.jl:642
Stacktrace:
[1] repo_and_version_of_pull_request_body(body::Nothing)
@ RegistryCI.TagBot ~/.julia/packages/RegistryCI/3KBMb/src/TagBot/TagBot.jl:48
```
This could be handled using a separate dispatch, but this approach seems more in line with the rest of the codebase. Just let me know if you'd prefer the dispatch implementation instead and I'll get this updated.
Fixes #503.
=> Gracefully handle pull requests without bodies

src/registry_testing.jl
Addresses https://github.com/JuliaRegistries/RegistryCI.jl/pull/514#discussion_r1317805452
=> `pairs()` is not necessary when iterating over a `Base.Dict`

Project.toml, src/registry_testing.jl
=> When yanking a version, only `yanked = true` is correct; `yank = true` (and other variants) are incorrect, so we should detect them

.github/workflows/ci_integration.yml, .github/workflows/ci_unit.yml
Because the public instance of Bors has been shut down.
=> CI: Migrate from Bors to GitHub Merge Queue

src/AutoMerge/guidelines.jl
This PR is created due to [this discussion](https://julialang.slack.com/archives/C6M4DQA5P/p1700666990252839). When a version skipping happens, the RegistryCI shows the following message:
> ... . The following guidelines were not met:
> 
> Does not meet sequential version number guideline: version 1.3.2 skips over 1.3.1
> Note that the guidelines are only required for the pull request to be merged automatically. However, **it is strongly recommended** to follow them, since otherwise the pull request needs to be manually reviewed and merged by a human.
In my opinion, this message gives the impression that version skipping is strictly prohibited. It seems to say that you should not do this, but if you did, you need to provide a convincing explanation for why you skipped some versions. …
=> Improve `_invalid_sequential_version` msg.

docs/src/guidelines.md, example_github_workflow_files/automerge.yml, src/AutoMerge/guidelines.jl, src/AutoMerge/pull_requests.jl, test/automerge-unit.jl
...by turning off the distance check whenever the label is applied. The github action should be updated to activate when labels are added, for best effect, as shown in the example yaml.
=> AutoMerge: Respect the `Override AutoMerge: name similarity is okay` label

src/AutoMerge/guidelines.jl, src/AutoMerge/util.jl
Follow-up to #516 
Once we are ready to re-enable the "Require `[compat]` for stdlib dependencies" feature", we just need to change the following value from `false` to `true`:
https://github.com/JuliaRegistries/RegistryCI.jl/blob/d4f84b521bab13f57b355a979120455e34db0954/src/AutoMerge/guidelines.jl#L5-L5
=> AutoMerge: temporarily disable the "Require `[compat]` for stdlib dependencies" feature"

.github/workflows/TagBot.yml, Project.toml
Also updates tagbot, so we have the best chances of actually getting a tag.
When we register this, we can include these release notes:
```
* Turn off stdlib compat requirement ([#540](https://github.com/JuliaRegistries/RegistryCI.jl/pull/540))
* Adds label-reading support for author-approval workflow ([#539](https://github.com/JuliaRegistries/RegistryCI.jl/pull/539)) and overriding the name similarity check ([#536](https://github.com/JuliaRegistries/RegistryCI.jl/pull/536))
```
We should only tag after landing #539 and #541
=> Bump version for release

Project.toml, src/AutoMerge/guidelines.jl
in #539 I placed the message in the wrong spot, as revealed by https://github.com/JuliaRegistries/General/pull/99875#issuecomment-1917615690, which still says
> Does not meet sequential version number guideline: version 3.1.3 skips over 3.1.2. If this was intentional, please leave a comment saying so. Otherwise please correct the version number in your package and re-trigger registration.
instead of the intended new message directing the author to approve if desired.
I've bumped the version here so we can release the bugfix right away.
=> Fix sequential version message

src/AutoMerge/guidelines.jl
noticed in https://github.com/JuliaRegistries/General/pull/99903
=> fix tiny typo in sequential merge instructions

src/AutoMerge/guidelines.jl, test/automerge-unit.jl
This part should not be overridable by labels. (Note this isn't a huge issue, since the consistency tests seem to catch this already, but it is helpful to have the logic clear here and to give a good message even if the label is applied removing the similarity check).
=> split out `guideline_name_match_check`

src/AutoMerge/guidelines.jl, test/automerge-unit.jl
Inspired by https://github.com/JuliaRegistries/General/pull/100209. Whether or not folks decide to allow the name PsychoJL.jl, all such names should require manual approval.
=> Don't automerge packages whose names end with jl

Project.toml, src/AutoMerge/guidelines.jl, src/AutoMerge/semver.jl, src/AutoMerge/types.jl, test/automerge-unit.jl
Fixes #562 
The basic idea of this PR is to take something out of the "exception" domain and move it into the "guideline failure" domain. This allows us to surface the underlying error back up to the user (in the form of the AutoMerge comment).
=> Correctly handle an edge case in the sequential version check

src/TagBot/TagBot.jl
Repos that use the `julia-vscode/testitem-workflow/.github/workflows/juliaci.yml` are also TagBot enabled.
=> Open tagbot trigger issues for testitem repos

Project.toml, src/AutoMerge/cron.jl
Currently, we don't update the labels regarding blocked/not-blocked unless the auto merge commit status is OK, the waiting period has elapsed, etc. This means many PRs that are blocked aren't labeled. It also means that the blocked label won't be properly removed in the following situation:
- the PR has automerge status passing, but a comment is blocking
- blocked label is added
- the pr is updated and automerge starts failing
- blocking comment is removed
- status quo: block label is *not* removed bc we don't get to the code that updates the label
- PR: block label is removed, since we update the block label first
This PR fixes it by moving the block check earlier, once we are confident it is a registration PR, so the label is updated reliably.
=> Move blocked label updating earlier

src/AutoMerge/guidelines.jl
Currently, the log message looks like this:
> [ Info: IMPORTANT: If you see any messages of the form "Error: Some registries failed to update"or "registry dirty", please disregard those messages. Those messages are normal and do not indicate an error.
Note that there is a space missing here:
```
update"or
```
This PR adds the missing space.
=> Fix a missing space in a log message

Project.toml
In preparation for a new release.
I'd like to get a new release out that includes #575.
I decided to consider #575 as a new feature, so I bumped the minor version number here.
=> Bump version number from 10.8.1 to 10.9.0

Project.toml, src/AutoMerge/cron.jl
Untested, but I presume this should fix https://github.com/JuliaRegistries/RegistryCI.jl/pull/573#discussion_r1875021374.
=> [AutoMerge] Do not add "blocked" label if already there

Project.toml, src/AutoMerge/guidelines.jl, test/automerge-unit.jl
This was suggested by @fredrikekre on Slack. I think it makes sense that if some folks maintain a detailed changelog, then it should suffice for them to point to it. I think it is good if we can keep the requirements minimally burdensome while achieving the outcome, so to me this seems like a good balance (since having a good changelog is a good outcome here).
=> allow "changelog" in release notes for breaking changelog guideline
